name: Create Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    uses: vantage6/vantage6-workflows/.github/workflows/algorithm-release.yml@5fa2c79619a7660dda02b2c80623fc010f66d661
    secrets: inherit
    with:
      docker_image: ghcr.io/vantage6/algorithm/summary
